# Programs
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = wofi

# Session environment
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = DESKTOP_SESSION,hyprland
env = NIXOS_OZONE_WL,1
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
