# Critical monitor config: do not change Samsung G9 line.
monitor=DP-2,5120x1440@240.00,0x0,1,bitdepth,10
monitor=HDMI-A-1,3840x2160@60,5120x0,1

# Workspace mapping per monitor.
workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
